### ISSUE TITLE
1-6 tasks 

### ISSUE THREAD

**Issue by usau-sh** [usau-sh/cpp_sirius#2]

**Comment by dzheltkov** [comment]
1) В CMakeLists.txt крайне желательно указывать `cmake_minimum_required` и `project`

2) Задания 1, 2, 3 зачтены.

3) Задание 4 не компилируется:
- Имя `CMakeLists.txt` с ошибкой,
-  в `main` файл `lodepng.h` подключается по с помощью `#include <lodepng>` но он находится не в папке, по которым осуществляется поиск с помощью такого `#include`. Нужно или в CMakeLists.txt добавить папку содержащую этот исходный файл в папку где осуществляется поиск заголовочных файлов, либо подключать иначе.
-  Кроме того, в конце этого файла не хватает `#endif`.

4) Так же в задании 4 не производится очистка аллоцируемой памяти для `arr_distances`. В общем, задание 4 не зачтено.

5) Задание 5, так как у вас не сданы в срок задания 1-3, заменяется на [задание 5*](https://bitbucket.org/dzheltkov/cpp_prak/src/master/task5star/), поэтому не зачтено.

6) Задание 6 полностью совпадает с предоставленным А. Юрченко, и потому не принимается, требуется альтернативная его реализация (или реализация [задания 6М](https://bitbucket.org/dzheltkov/cpp_prak/src/master/task6M/)).
Кроме того, задание 7 заменяется на индивидуальное - примерно как [задание 7М](https://bitbucket.org/dzheltkov/cpp_prak/src/master/task7M/), только необходимо реализовать [стабилизированный метод бисопряжённых градиентов](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%B1%D0%B8%D0%BB%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4_%D0%B1%D0%B8%D1%81%D0%BE%D0%BF%D1%80%D1%8F%D0%B6%D1%91%D0%BD%D0%BD%D1%8B%D1%85_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2).
